### ISSUE TITLE
Duplicate package?

### ISSUE THREAD

**Issue by Baklap4** [Sir-Kyle-Richardson/OSRS-Flipper#2]
What's gonna be the difference between this and https://github.com/Belieal/flipping-utilities that project?

**Comment by Sir-Kyle-Richardson** [comment]
flipping-utilities requires margin checking an item before considering it a flip. This package aims to allow flipping without margin checking

**Comment by Sir-Kyle-Richardson** [comment]
I've also ran into issues where the data for flipping-utilities became corrupted/lost; main reason I created this plugin
