### ISSUE TITLE
TradePersister: hardcoded path separator

### ISSUE THREAD

**Issue by Hello71** [Sir-Kyle-Richardson/OSRS-Flipper#3]
https://github.com/Sir-Kyle-Richardson/OSRS-Flipper/blob/f54849bcaa378e8060efbb6e652b590fddb73ac9/src/main/java/com/flipper/helpers/TradePersister.java#L77

this only works on windows

**Comment by wwaller** [comment]
I'm fixing this in my open PR. Do I need to make it conditional on OS? I only have a macbook

**Comment by Hello71** [comment]
forward slashes work on all (modern) platforms. there's File.separator, but that's mainly for printing or interfacing with poorly written programs. but really this should be `Paths.get(directory, filename)`. https://docs.oracle.com/javase/7/docs/api/java/nio/file/Paths.html#get(java.lang.String,%20java.lang.String...)

**Comment by Hello71** [comment]
or better, directory should be a Path, not an old-fashioned File, then use `directory.resolve(filename)` like it says in the documentation.

**Comment by wwaller** [comment]
I'm going to wait for the author to respond to the bat signal before thinking anymore about this.
